//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("DuelMasters.Engine")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+1eb1658f2880769acee9b70bb5ded6171b666a09")]
[assembly: System.Reflection.AssemblyProductAttribute("DuelMasters.Engine")]
[assembly: System.Reflection.AssemblyTitleAttribute("DuelMasters.Engine")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// MSBuild WriteCodeFragment 繧ｯ繝ｩ繧ｹ縺ｫ繧医▲縺ｦ逕滓・縺輔ｌ縺ｾ縺励◆縲・



