// <auto-generated> M15.16r SnapshotSanitizer fixed for current Record schema </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;

namespace DMRules.Engine.Tracing
{
    internal static class M15_16r_SnapshotSanitizer
    {
        public static IEnumerable<TemplateParseTrace.Record> RemoveShieldTriggerPrefix(this IEnumerable<TemplateParseTrace.Record> src)
        {
            if (src == null)
                yield break;

            foreach (var r in src)
            {
                var copy = new TemplateParseTrace.Record
                {
                    CardName = r.CardName,
                    Tokens = (r.Tokens ?? new List<string>())
                                    .Select(t => t != null && t.StartsWith("ShieldTrigger:")
                                                 ? t.Substring("ShieldTrigger:".Length)
                                                 : t)
                                    .ToList(),
                    Unresolved = r.Unresolved != null ? new List<string>(r.Unresolved) : new List<string>(),
                    Timestamp = r.Timestamp
                };
                yield return copy;
            }
        }
    }
}
