// <auto-generated>
// M15.4b-1: Parser-oriented normalization utilities (conservative)
// Goal: reduce surface variance WITHOUT changing semantics.
// </auto-generated>
using System;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace DMRules.Engine.TextParsing
{
    public static class CardTextNormalizer
    {
        // Visible for tests
        public static string NormalizeForParsing(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return string.Empty;

            // 1) Strip set markers like \\u300A...\\u300B, 【...】 (legacy compat)
            s = CardTextTemplates.SetMarkerStrip(s);

            // 2) Unicode normalization to NFKC (width folding)
            s = s.Normalize(NormalizationForm.FormKC);

            // 3) Unify whitespace (incl. full-width spaces)
            s = Regex.Replace(s, @"\s+", " ").Trim();

            // 4) Canonicalize punctuation micro-variance
            s = s.Replace("，", "、").Replace(",", "、");
            s = s.Replace("．", "。").Replace(".", "。");

            // 5) Canonicalize common turns / period phrases
            s = Regex.Replace(s, @"この?ターンの終わりまで", "ターンの終わりまで");
            s = Regex.Replace(s, @"次の相手のターンのはじめまで", "次の相手のターンの間");
            s = Regex.Replace(s, @"次の自分のターンのはじめまで", "次の自分のターンの間");

            // 6) Canonicalize quantifiers & options
            s = Regex.Replace(s, @"いずれかの?1体", "いずれか1体");
            s = Regex.Replace(s, @"最大\s*(\d+)", "最大$1");

            // 7) Remove redundant quotes/specials used in DB text
            s = s.Replace("「", "『").Replace("」", "』"); // unify to corner quotes

            s = System.Text.RegularExpressions.Regex.Replace(s, @"\s{2,}", " ").Trim();
            s = System.Text.RegularExpressions.Regex.Replace(s, @"\s{2,}", " ").Trim();
                        // M15.4b3: 強化された正規化（IgnoreCase / 可変空白）
            s = System.Text.RegularExpressions.Regex.Replace(s, @"この?\s*ターン\s*の\s*終わり\s*まで", "ターンの終わりまで", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            s = System.Text.RegularExpressions.Regex.Replace(s, @"次の\s*相手\s*の\s*ターン\s*の\s*はじめまで", "次の相手のターンの間", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            s = System.Text.RegularExpressions.Regex.Replace(s, @"次の\s*自分\s*の\s*ターン\s*の\s*はじめまで", "次の自分のターンの間", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            s = System.Text.RegularExpressions.Regex.Replace(s, @"\s{2,}", " ");
                        // M15.5: 「のはじめまで」→「の間」 正規化
            s = System.Text.RegularExpressions.Regex.Replace(s, @"次の\s*相手\s*の\s*ターン\s*の\s*はじめまで", "次の相手のターンの間", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            s = System.Text.RegularExpressions.Regex.Replace(s, @"次の\s*自分\s*の\s*ターン\s*の\s*はじめまで", "次の自分のターンの間", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
                        // M15FixStrict: はじめまで→間
            s = System.Text.RegularExpressions.Regex.Replace(
                s, @"次の\s*相手\s*の\s*ターン\s*の\s*はじめまで", "次の相手のターンの間",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            s = System.Text.RegularExpressions.Regex.Replace(
                s, @"次の\s*自分\s*の\s*ターン\s*の\s*はじめまで", "次の自分のターンの間",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            // M15FixStrict: strip decorative brackets (U+300A/U+300B)
            s = s.Replace("\u300A", "").Replace("\u300B", "");

            return s;
        }
    }
}








